# Site settings
title: Command Shift
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  iOS development and other nonsense
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: "/blog/:year/:month/:day/:title/"
url: "http://commandshift.co.uk" # the base hostname & protocol for your site
excerpt_separator: <!--more-->
twitter_username: richturton
github_username:  jrturton
author: Richard Turton
google_analytics_tracking_id: UA-36924055-1

# Code formatting
highlighter: rouge

gems:
    - jekyll-sitemap